import { create } from 'zustand';

export type Product = {
  name: string;
  price: number;
  affiliateUrl: string;
  shop: 'Tokopedia' | 'Shopee';
};

export type Design = {
  id: string;
  roomType: string;
  style: string;
  dimensions: string;
  prompt: string;
  imageUrl: string;
  products: Product[];
  createdAt: string;
};

type DesignState = {
  designs: Design[];
  addDesign: (design: Design) => void;
  removeDesign: (id: string) => void;
  clearDesigns: () => void;
};

const encodeSvg = (svg: string) => `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`;

const roomSvg = ({
  title,
  colors,
  label,
}: {
  title: string;
  colors: string[];
  label: string;
}) => {
  const [bg, glow, accent] = colors;
  return encodeSvg(`
    <svg width="1200" height="900" viewBox="0 0 1200 900" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0%" stop-color="${bg}" />
          <stop offset="100%" stop-color="#120b1f" />
        </linearGradient>
        <radialGradient id="glow" cx="50%" cy="20%" r="70%">
          <stop offset="0%" stop-color="${glow}" stop-opacity="0.65" />
          <stop offset="100%" stop-color="${glow}" stop-opacity="0" />
        </radialGradient>
      </defs>
      <rect width="1200" height="900" rx="36" fill="url(#bg)" />
      <rect x="70" y="60" width="1060" height="740" rx="32" fill="rgba(255,255,255,0.04)" stroke="rgba(255,255,255,0.10)" />
      <ellipse cx="600" cy="140" rx="460" ry="260" fill="url(#glow)" />
      <rect x="130" y="660" width="940" height="90" rx="26" fill="rgba(255,255,255,0.07)" />
      <rect x="170" y="540" width="220" height="210" rx="26" fill="rgba(255,255,255,0.12)" stroke="rgba(255,255,255,0.12)" />
      <rect x="424" y="420" width="360" height="330" rx="28" fill="rgba(255,255,255,0.08)" stroke="rgba(255,255,255,0.12)" />
      <rect x="828" y="470" width="220" height="280" rx="26" fill="rgba(255,255,255,0.10)" stroke="rgba(255,255,255,0.12)" />
      <rect x="470" y="180" width="250" height="180" rx="26" fill="${accent}" fill-opacity="0.35" stroke="rgba(255,255,255,0.15)" />
      <path d="M150 640H1050" stroke="rgba(255,255,255,0.08)" stroke-width="12" stroke-linecap="round" />
      <path d="M260 510H340" stroke="${accent}" stroke-width="10" stroke-linecap="round" />
      <path d="M874 510H1008" stroke="${accent}" stroke-width="10" stroke-linecap="round" />
      <circle cx="960" cy="150" r="50" fill="rgba(255,255,255,0.12)" stroke="rgba(255,255,255,0.16)" />
      <text x="120" y="120" fill="#F5F3FF" font-family="Inter, Arial, sans-serif" font-size="44" font-weight="700">${title}</text>
      <text x="120" y="168" fill="#C4B5FD" font-family="Inter, Arial, sans-serif" font-size="24">${label}</text>
      <text x="120" y="826" fill="#A78BFA" font-family="Inter, Arial, sans-serif" font-size="22">Generated by KOST.AI</text>
    </svg>
  `);
};

const tokopediaUrl = (query: string) =>
  `https://www.tokopedia.com/search?st=product&q=${encodeURIComponent(query)}`;

const shopeeUrl = (query: string) =>
  `https://shopee.co.id/search?keyword=${encodeURIComponent(query)}`;

const formatId = (value: string) =>
  value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

export const seedDesigns: Design[] = [
  {
    id: 'japandi-3x3',
    roomType: 'Kamar Tidur',
    style: 'Japandi',
    dimensions: '3x3 m',
    prompt: 'Kamar 3x3 Japandi dengan nuansa tenang, tatami bed, penyimpanan vertikal, dan pencahayaan hangat.',
    imageUrl: roomSvg({
      title: 'Kamar 3x3 Japandi',
      colors: ['#1B1330', '#8B5CF6', '#C4B5FD'],
      label: 'Tatami bed • folding desk • vertical storage',
    }),
    products: [
      {
        name: 'Ranjang platform tatami 120x200',
        price: 2590000,
        affiliateUrl: tokopediaUrl('ranjang tatami minimalis 120x200'),
        shop: 'Tokopedia',
      },
      {
        name: 'Meja lipat dinding kayu',
        price: 785000,
        affiliateUrl: shopeeUrl('meja lipat dinding kayu minimalis'),
        shop: 'Shopee',
      },
      {
        name: 'Rak vertikal 5 susun',
        price: 540000,
        affiliateUrl: tokopediaUrl('rak vertikal besi minimalis'),
        shop: 'Tokopedia',
      },
    ],
    createdAt: '2026-05-02T02:00:00.000Z',
  },
  {
    id: 'living-industrial-mini',
    roomType: 'Ruang Tamu',
    style: 'Industrial',
    dimensions: '3x4 m',
    prompt: 'Ruang tamu mini industrial dengan exposed bulb, metal rack, leather pouf, dan aksen gelap.',
    imageUrl: roomSvg({
      title: 'Ruang Tamu Mini Industrial',
      colors: ['#151515', '#F59E0B', '#D4A373'],
      label: 'Exposed bulb • metal rack • leather pouf',
    }),
    products: [
      {
        name: 'Lampu gantung bohlam exposed',
        price: 325000,
        affiliateUrl: tokopediaUrl('lampu gantung bohlam industrial'),
        shop: 'Tokopedia',
      },
      {
        name: 'Rak besi hitam 4 tingkat',
        price: 980000,
        affiliateUrl: shopeeUrl('rak besi hitam industrial'),
        shop: 'Shopee',
      },
      {
        name: 'Pouf kulit sintetis cokelat',
        price: 420000,
        affiliateUrl: tokopediaUrl('pouf kulit sintetis cokelat'),
        shop: 'Tokopedia',
      },
    ],
    createdAt: '2026-05-01T18:00:00.000Z',
  },
  {
    id: 'kitchen-scandi-mini',
    roomType: 'Dapur Mini',
    style: 'Skandinavia',
    dimensions: '2x3 m',
    prompt: 'Dapur kos skandinavia yang terang, white tiles, rak kayu, dan spice rack yang rapi.',
    imageUrl: roomSvg({
      title: 'Dapur Kos Skandinavia',
      colors: ['#101826', '#60A5FA', '#A7F3D0'],
      label: 'White tiles • wooden shelves • spice rack',
    }),
    products: [
      {
        name: 'Rak dinding kayu pinus',
        price: 350000,
        affiliateUrl: shopeeUrl('rak dinding kayu pinus dapur'),
        shop: 'Shopee',
      },
      {
        name: 'Set toples bumbu kaca',
        price: 210000,
        affiliateUrl: tokopediaUrl('toples bumbu kaca dapur'),
        shop: 'Tokopedia',
      },
      {
        name: 'Stiker dinding white tile',
        price: 145000,
        affiliateUrl: shopeeUrl('stiker dinding white tile dapur'),
        shop: 'Shopee',
      },
    ],
    createdAt: '2026-05-01T09:30:00.000Z',
  },
  {
    id: 'work-zone-2x2',
    roomType: 'Area Kerja',
    style: 'Minimalis',
    dimensions: '2x2 m',
    prompt: 'Area kerja produktif 2x2 dengan wall-mounted desk, pegboard, monitor arm, dan lighting fokus.',
    imageUrl: roomSvg({
      title: 'Area Kerja Produktif 2x2',
      colors: ['#0F172A', '#8B5CF6', '#A78BFA'],
      label: 'Wall desk • pegboard • monitor arm',
    }),
    products: [
      {
        name: 'Meja tempel dinding compact',
        price: 620000,
        affiliateUrl: tokopediaUrl('meja tempel dinding minimalis'),
        shop: 'Tokopedia',
      },
      {
        name: 'Pegboard organizer 60 cm',
        price: 265000,
        affiliateUrl: shopeeUrl('pegboard organizer meja kerja'),
        shop: 'Shopee',
      },
      {
        name: 'Arm monitor adjustable',
        price: 480000,
        affiliateUrl: tokopediaUrl('monitor arm adjustable'),
        shop: 'Tokopedia',
      },
    ],
    createdAt: '2026-05-01T07:45:00.000Z',
  },
  {
    id: 'boho-studio-corner',
    roomType: 'Ruang Tamu',
    style: 'Bohemian',
    dimensions: '3x3 m',
    prompt: 'Sudut santai bohemian dengan tekstur rotan, karpet pattern, tanaman kecil, dan sofa rendah.',
    imageUrl: roomSvg({
      title: 'Sudut Bohemian Hangat',
      colors: ['#1F1235', '#F472B6', '#FCD34D'],
      label: 'Rattan • patterned rug • greenery',
    }),
    products: [
      {
        name: 'Karpet pattern 160x230',
        price: 670000,
        affiliateUrl: shopeeUrl('karpet pattern bohemian'),
        shop: 'Shopee',
      },
      {
        name: 'Kursi rotan rendah',
        price: 890000,
        affiliateUrl: tokopediaUrl('kursi rotan rendah boho'),
        shop: 'Tokopedia',
      },
      {
        name: 'Rak tanaman gantung',
        price: 230000,
        affiliateUrl: shopeeUrl('rak tanaman gantung minimalis'),
        shop: 'Shopee',
      },
    ],
    createdAt: '2026-04-30T20:10:00.000Z',
  },
  {
    id: 'bathroom-clean-zinc',
    roomType: 'Kamar Mandi',
    style: 'Minimalis',
    dimensions: '2x2 m',
    prompt: 'Kamar mandi kecil yang clean dengan storage gantung, cermin besar, dan material anti lembap.',
    imageUrl: roomSvg({
      title: 'Kamar Mandi Clean',
      colors: ['#0B1020', '#94A3B8', '#E879F9'],
      label: 'Anti lembap • cermin besar • storage gantung',
    }),
    products: [
      {
        name: 'Cermin LED bulat',
        price: 575000,
        affiliateUrl: tokopediaUrl('cermin led bulat kamar mandi'),
        shop: 'Tokopedia',
      },
      {
        name: 'Rak gantung anti karat',
        price: 155000,
        affiliateUrl: shopeeUrl('rak gantung kamar mandi anti karat'),
        shop: 'Shopee',
      },
      {
        name: 'Keranjang laundry slim',
        price: 180000,
        affiliateUrl: tokopediaUrl('keranjang laundry slim minimalis'),
        shop: 'Tokopedia',
      },
    ],
    createdAt: '2026-04-29T15:00:00.000Z',
  },
];

export const buildGeneratedDesign = (input: {
  roomType: string;
  dimensions: string;
  style: string;
  color: string;
}) => {
  const id = `${formatId(input.roomType)}-${formatId(input.dimensions)}-${formatId(input.style)}-${Date.now().toString(36)}`;
  const title = `${input.roomType} ${input.style}`;

  const paletteMap: Record<string, [string, string, string]> = {
    Minimalis: ['#10121B', '#8B5CF6', '#D8B4FE'],
    Japandi: ['#18161D', '#A78BFA', '#C6F6D5'],
    Industrial: ['#151515', '#F59E0B', '#E5E7EB'],
    Skandinavia: ['#0F172A', '#60A5FA', '#DBEAFE'],
    Bohemian: ['#25153A', '#EC4899', '#FDE68A'],
    Modern: ['#121826', '#8B5CF6', '#22D3EE'],
  };

  const colors = paletteMap[input.style] ?? paletteMap.Minimalis;
  return {
    id,
    roomType: input.roomType,
    style: input.style,
    dimensions: input.dimensions,
    prompt: `${input.roomType} ${input.style} untuk ruang ${input.dimensions} dengan preferensi warna ${input.color}. Fokus pada solusi hemat tempat, lighting lembut, dan produk yang mudah dibeli di marketplace Indonesia.`,
    imageUrl: roomSvg({
      title,
      colors,
      label: `${input.color} • compact layout • AI draft`,
    }),
    products: [
      {
        name: `${input.style} sofa / bed compact`,
        price: 1890000,
        affiliateUrl: tokopediaUrl(`${input.style.toLowerCase()} compact furniture`),
        shop: 'Tokopedia',
      },
      {
        name: 'Rak multifungsi hemat tempat',
        price: 430000,
        affiliateUrl: shopeeUrl('rak multifungsi hemat tempat'),
        shop: 'Shopee',
      },
      {
        name: 'Lampu ambient hangat',
        price: 275000,
        affiliateUrl: tokopediaUrl('lampu ambient hangat minimalis'),
        shop: 'Tokopedia',
      },
    ] as Product[],
    createdAt: new Date().toISOString(),
  } satisfies Design;
};

export const useDesignStore = create<DesignState>((set) => ({
  designs: seedDesigns,
  addDesign: (design) => set((state) => ({ designs: [design, ...state.designs] })),
  removeDesign: (id) => set((state) => ({ designs: state.designs.filter((design) => design.id !== id) })),
  clearDesigns: () => set({ designs: seedDesigns }),
}));

export const getDesignById = (id: string) => seedDesigns.find((design) => design.id === id);

export const marketplaceSearch = (shop: 'Tokopedia' | 'Shopee', query: string) =>
  shop === 'Tokopedia' ? tokopediaUrl(query) : shopeeUrl(query);
