"use client";

import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { ArrowLeft, CheckCircle2, Play, Sparkles } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { buildGeneratedDesign, useDesignStore } from '@/lib/store';

export default function GenerateClient() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const addDesign = useDesignStore((state) => state.addDesign);
  const [processing, setProcessing] = useState(true);
  const [progress, setProgress] = useState(12);

  const queryKey = searchParams.toString();
  const input = useMemo(
    () => ({
      roomType: searchParams.get('roomType') ?? 'Kamar Tidur',
      dimensions: searchParams.get('dimensions') ?? '3x3',
      style: searchParams.get('style') ?? 'Japandi',
      color: searchParams.get('color') ?? 'Netral hangat',
    }),
    [queryKey],
  );

  const generated = useMemo(() => buildGeneratedDesign(input), [queryKey]);

  useEffect(() => {
    setProcessing(true);
    setProgress(12);

    const timer = window.setTimeout(() => {
      setProcessing(false);
      setProgress(100);
    }, 1800);

    const progressTicker = window.setInterval(() => {
      setProgress((value) => Math.min(92, value + 14));
    }, 220);

    return () => {
      window.clearTimeout(timer);
      window.clearInterval(progressTicker);
    };
  }, [generated.id]);

  const saveDesign = () => {
    addDesign(generated);
    router.push(`/design/${generated.id}`);
  };

  return (
    <main className="shell" style={{ padding: '40px 0 32px' }}>
      <div className="button-row" style={{ marginBottom: 18 }}>
        <Link href="/" className="pill">
          <ArrowLeft size={14} />
          Kembali ke generator
        </Link>
        <span className="tag">Simulasi AI rendering</span>
      </div>

      <section className="grid-2">
        <div className="panel" style={{ padding: 24 }}>
          <span className="kicker">Sedang memproses konsep desain</span>
          <h1 className="h1" style={{ fontSize: 'clamp(30px, 4vw, 48px)' }}>
            KOST.AI sedang menyusun layout compact untuk {input.roomType.toLowerCase()}.
          </h1>
          <p className="lead">
            Kami tidak memanggil Stable Diffusion sungguhan, jadi halaman ini menampilkan mockup CSS yang tetap terasa hidup:
            ada progress bar, animasi, furniture overlay, dan rekomendasi produk yang relevan.
          </p>

          <div className="timeline" style={{ marginTop: 22 }}>
            <div className="timeline-item">
              <div className="row" style={{ marginBottom: 8 }}>
                <strong>Phase 1 — memahami ruang</strong>
                <span className="muted">{processing ? 'aktif' : 'selesai'}</span>
              </div>
              <div className="loading-bars" aria-hidden="true">
                <span />
                <span />
                <span />
                <span />
                <span />
              </div>
            </div>
            <div className="timeline-item">
              <div className="row" style={{ marginBottom: 10 }}>
                <strong>Phase 2 — komposisi visual</strong>
                <span className="tag">{progress}%</span>
              </div>
              <div style={{ height: 10, borderRadius: 999, background: 'rgba(255,255,255,.06)', overflow: 'hidden' }}>
                <div
                  style={{
                    height: '100%',
                    width: `${progress}%`,
                    borderRadius: 999,
                    background: 'linear-gradient(90deg, #8b5cf6, #c084fc)',
                    transition: 'width 220ms ease',
                  }}
                />
              </div>
            </div>
            <div className="timeline-item">
              <div className="row" style={{ marginBottom: 8 }}>
                <strong>Prompt ringkas</strong>
                <span className="muted">dihasilkan otomatis</span>
              </div>
              <p className="card-copy">{generated.prompt}</p>
            </div>
          </div>

          <div className="button-row" style={{ marginTop: 18 }}>
            <button className="button" type="button" onClick={saveDesign}>
              <CheckCircle2 size={18} />
              Simpan desain
            </button>
            <Link href={`/design/${generated.id}`} className="button button-ghost">
              Buka detail mockup
              <Play size={16} />
            </Link>
          </div>
        </div>

        <div className="panel" style={{ padding: 24 }}>
          <div className="row" style={{ marginBottom: 18 }}>
            <span className="badge">
              <Sparkles size={15} />
              Generated by AI
            </span>
            <span className="tag">{generated.style}</span>
          </div>

          <div className="room-mock">
            <div className="room-grid" />
            <div className="room-layer" style={{ inset: '12% 14% 14% 12%', background: 'linear-gradient(180deg, rgba(139,92,246,.34), rgba(139,92,246,.08))' }} />
            <div className="room-layer" style={{ inset: '20% 58% 28% 56%', background: 'linear-gradient(180deg, rgba(255,255,255,.15), rgba(255,255,255,.04))' }} />
            <div className="room-layer" style={{ inset: '54% 12% 18% 38%', background: 'linear-gradient(180deg, rgba(192,132,252,.22), rgba(192,132,252,.08))' }} />
            <div className="room-layer" style={{ inset: '50% 64% 26% 18%', background: 'linear-gradient(180deg, rgba(255,255,255,.12), rgba(255,255,255,.04))' }} />
            <div className="room-layer" style={{ inset: '12% 20% auto auto', width: 92, height: 92, borderRadius: 999, background: 'radial-gradient(circle, rgba(255,255,255,.4), rgba(255,255,255,.06))' }} />
            <div style={{ position: 'absolute', inset: 18, display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
              <div className="button-row" style={{ justifyContent: 'space-between' }}>
                <span className="tag">AI room visualization</span>
                <span className="badge">{input.roomType}</span>
              </div>
              <div className="panel-soft" style={{ padding: 16, maxWidth: 360 }}>
                <div className="muted" style={{ fontSize: 12, marginBottom: 6 }}>Layout notes</div>
                <strong>{input.dimensions} • {input.style}</strong>
                <p className="card-copy" style={{ marginTop: 8 }}>
                  Fokus pada sirkulasi, storage vertikal, dan akses cepat ke produk yang cocok untuk ruang kecil.
                </p>
              </div>
            </div>
          </div>

          <div className="grid-3" style={{ marginTop: 18 }}>
            {generated.products.map((product) => (
              <div className="timeline-item" key={product.name}>
                <div className="muted" style={{ fontSize: 12, marginBottom: 6 }}>{product.shop}</div>
                <strong>{product.name}</strong>
                <div style={{ marginTop: 8, color: '#f5d0fe', fontWeight: 700 }}>{new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(product.price)}</div>
              </div>
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}
