"use client";

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { ArrowLeft, ExternalLink, ShoppingCart } from 'lucide-react';
import { useMemo } from 'react';
import { marketplaceSearch, seedDesigns, useDesignStore } from '@/lib/store';

const formatter = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 });

export default function DesignDetailPage() {
  const params = useParams<{ id: string }>();
  const designs = useDesignStore((state) => state.designs);
  const design = useMemo(
    () => designs.find((item) => item.id === params.id) ?? seedDesigns.find((item) => item.id === params.id),
    [designs, params.id],
  );

  if (!design) {
    return (
      <main className="shell" style={{ padding: '44px 0 32px' }}>
        <Link href="/" className="pill">
          <ArrowLeft size={14} />
          Kembali
        </Link>
        <div className="panel" style={{ padding: 24, marginTop: 18 }}>
          <h1 className="h1" style={{ fontSize: 36 }}>Desain tidak ditemukan</h1>
          <p className="lead">Coba buka desain dari galeri, atau buat mockup baru dari halaman generator.</p>
        </div>
      </main>
    );
  }

  return (
    <main className="shell" style={{ padding: '42px 0 32px' }}>
      <div className="button-row" style={{ marginBottom: 18 }}>
        <Link href="/" className="pill">
          <ArrowLeft size={14} />
          Kembali ke beranda
        </Link>
        <span className="tag">Detail desain</span>
      </div>

      <section className="grid-2">
        <div className="panel" style={{ padding: 24 }}>
          <div className="row" style={{ marginBottom: 18 }}>
            <div>
              <span className="kicker">{design.roomType}</span>
              <h1 className="h1" style={{ fontSize: 'clamp(30px, 4vw, 48px)', marginBottom: 8 }}>
                {design.roomType} {design.style}
              </h1>
              <div className="button-row">
                <span className="tag">{design.dimensions}</span>
                <span className="tag">{design.style}</span>
                <span className="tag">Purple accent</span>
              </div>
            </div>
          </div>

          <div className="room-mock" style={{ marginTop: 8 }}>
            <img
              src={design.imageUrl}
              alt={`${design.roomType} ${design.style}`}
              style={{ width: '100%', height: '100%', objectFit: 'cover', position: 'absolute', inset: 0, opacity: 0.92 }}
            />
            <div style={{ position: 'absolute', inset: 18, display: 'flex', justifyContent: 'space-between', alignItems: 'start', pointerEvents: 'none' }}>
              <span className="badge">Generated by AI</span>
              <span className="tag">{new Date(design.createdAt).toLocaleDateString('id-ID')}</span>
            </div>
          </div>

          <div style={{ marginTop: 18 }}>
            <h3 style={{ margin: '0 0 8px' }}>Prompt desain</h3>
            <p className="card-copy">{design.prompt}</p>
          </div>
        </div>

        <div className="panel" style={{ padding: 24 }}>
          <div className="section-head" style={{ marginBottom: 10 }}>
            <div>
              <h2 style={{ fontSize: 24 }}>Produk rekomendasi</h2>
              <p>Semua tombol mengarah ke pencarian marketplace agar mudah dibandingkan.</p>
            </div>
          </div>

          <div className="timeline">
            {design.products.map((product) => {
              const tokoUrl = marketplaceSearch('Tokopedia', product.name);
              const shopeeUrl = marketplaceSearch('Shopee', product.name);
              return (
                <article className="timeline-item" key={product.name}>
                  <div className="row" style={{ alignItems: 'start' }}>
                    <div style={{ flex: 1 }}>
                      <div className="muted" style={{ fontSize: 12, marginBottom: 8 }}>{product.shop}</div>
                      <h3 style={{ margin: '0 0 8px', fontSize: 18 }}>{product.name}</h3>
                      <div style={{ color: '#f5d0fe', fontWeight: 800, fontSize: 18 }}>{formatter.format(product.price)}</div>
                    </div>
                    <div className="tag">Affiliate-style</div>
                  </div>

                  <div className="button-row" style={{ marginTop: 14 }}>
                    <a className="button" href={tokoUrl} target="_blank" rel="noreferrer">
                      <ShoppingCart size={16} />
                      Beli di Tokopedia
                    </a>
                    <a className="button button-ghost" href={shopeeUrl} target="_blank" rel="noreferrer">
                      <ExternalLink size={16} />
                      Beli di Shopee
                    </a>
                  </div>
                </article>
              );
            })}
          </div>

          <div className="timeline-item" style={{ marginTop: 18 }}>
            <div className="row" style={{ marginBottom: 8 }}>
              <strong>Total estimasi</strong>
              <span className="tag">
                {formatter.format(design.products.reduce((sum, product) => sum + product.price, 0))}
              </span>
            </div>
            <p className="card-copy">
              Paket ini dirancang untuk ruang kecil: satu item utama, storage hemat tempat, dan aksen lighting yang bikin ruangan terasa lebih premium.
            </p>
          </div>
        </div>
      </section>
    </main>
  );
}
